# Generated by Django 4.2.4 on 2025-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
            ],
        ),
    ]
